name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Build npm package
        run: |
          npm ci
          npm pack
        env:
          CI: true
      - uses: actions/upload-artifact@v4
        with:
          name: vite-plugin-openfl
          path: vite-plugin-openfl-*.tgz
          if-no-files-found: error
      - run: npm link
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - name: Install Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install genes --quiet
      - name: Build samples/basic
        working-directory: samples/basic
        run: |
          npm link vite-plugin-openfl
          npm install
          npm run build
      - name: Build samples/genes
        working-directory: samples/genes
        run: |
          npm link vite-plugin-openfl
          npm install
          npm run build
      - name: Build samples/rollup
        working-directory: samples/rollup
        run: |
          npm link vite-plugin-openfl
          npm install
          npm run build
